spring:
    application:
        name: 'fornecedor'
    datasource:
        plataform: postgres
        url: jdbc:postgresql://localhost:5432/fornecedor_ms
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        format-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8081
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka